version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk

    working_directory: ~/fabric-beta-publisher-plugin

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-

    - run: mvn clean install findbugs:check -e

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    - store_artifacts:
        path: target/fabric-beta-publisher.hpi
